myproject/chat/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path("", views.index, name="index"),
    path("<str:room_name>/", views.room, name="room"),
    
]

myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include,re_path
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve
urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    path('admin/', admin.site.urls),
    path('',views.homepage),
    path('about/',views.about),
    path('posts/',include('post.urls')),
    path('users/',include('users.urls')),
    path("chat/", include("chat.urls")),

]
#urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

myproject/post/urls.py
from django.urls import path
from . import views
app_name='posts'
urlpatterns = [
    path('',views.posts_list,name="list"),
    path('new-post/',views.post_new,name="new-post"),

    path('<slug:slug>',views.post_page,name="page"),

]

myproject/users/urls.py
from django.urls import path
from . import views
app_name='users'
urlpatterns = [
    path('',views.users_list,name="list"),
    path('<int:userid>',views.user_page,name="page"),
    path('register',views.user_register,name="register"),
    path('login',views.user_login,name="login"),
    path('logout',views.user_logout,name="logout")
]

myproject/chat/models.py
from django.db import models
from django.contrib.auth.models import User

class Chat(models.Model):
    body=models.TextField()
    date=models.DateField(auto_now_add=True)
    #author=models.ForeignKey(User,on_delete=models.CASCADE,default=None)
    room_name=models.CharField(max_length=15)
    def __str__(self):
        return self.body

myproject/post/models.py
from django.db import models
from django.contrib.auth.models import User
class Post(models.Model):
    title=models.CharField(max_length=75)
    body=models.TextField()
    slug=models.SlugField()
    date=models.DateTimeField(auto_now_add=True)
    banner=models.ImageField(default='fallback.png',blank=True)
    author=models.ForeignKey(User,on_delete=models.CASCADE,default=None)
    def __str__(self):
        return self.title

myproject/users/models.py
from django.db import models

class Users(models.Model):
    name=models.CharField(max_length=20)
    userid=models.IntegerField(default=0)
    date=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

myproject/post/forms.py
from django import forms
from . import models

class CreatePost(forms.ModelForm):
    class Meta:
        model=models.Post
        fields=["title","body","slug","banner"]

myproject/chat/views.py
from django.shortcuts import render,redirect
from .models import Chat,User
from django.contrib.auth.decorators import login_required

@login_required(login_url="/users/login")
def index(request):
    return render(request, "chat/index.html")

@login_required(login_url="/users/login")
def room(request,room_name):
    chats=Chat.objects.filter(room_name=room_name)
    return render(request,"chat/room.html",{"room_name":room_name,"chats":chats})

myproject/myproject/views.py
from django.shortcuts import render

def homepage(request):
    return render(request,'homepage.html')


def about(request):
    return render(request,'about.html')

myproject/post/views.py
from django.shortcuts import render,redirect
from .models import Post
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import forms
# Create your views here.
def posts_list(request):
    posts=Post.objects.all().order_by('-date')

    return render(request,'posts/posts_list.html',{'posts':
                                                   posts})
def post_page(request,slug):
    post=Post.objects.get(slug=slug)
    return render(request,'posts/post_page.html',{'post':
                                                   post})


@login_required(login_url="/users/login")
def post_new(request):

    if request.method=="POST":
        form=forms.CreatePost(request.POST,request.FILES)
        if form.is_valid():
            newpost=form.save(commit=False)
            newpost.author=request.user
            newpost.save()
            return redirect('posts:list')
        
    else:
        form=forms.CreatePost()


    return render(request,'posts/post_new.html',{'form':form})

myproject/users/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from .models import Users
from django.contrib.auth import login,logout
def users_list(request):
    users=Users.objects.all().order_by("-date")
    return render(request,'users/user_list.html',{'users':users})
def user_page(request,userid):
    user=Users.objects.get(userid=userid)
    return render(request,'users/user_page.html',{'user':user})
def user_register(request):
    if request.method=="POST":
        form=UserCreationForm(request.POST)
        if form.is_valid():
            login(request,form.save())
            return redirect("posts:list")
    else:
        form=UserCreationForm()
    return render(request,'register.html',{'form':form})

def user_login(request):
    if request.method=="POST":
        form=AuthenticationForm(data=request.POST)
        if form.is_valid():
            login(request,form.get_user())

            if "next" in request.POST:
                return redirect(request.POST.get('next'))
            return redirect("posts:list")
    else:

        form=AuthenticationForm()

    return render(request,'login.html',{'form':form})
def user_logout(request):
    if request.method=="POST":
        logout(request)
        return redirect("/")

myproject/chat/templates/chat/index.html
{% extends 'layout.html' %}
{% block title %}
Chat Rooms
{% endblock title %}
{% block content %}
<h1>What chat room would you like to enter?</h1>
    <input id="room-name-input" type="text" size="100"><br>
    <input id="room-name-submit" type="button" value="Enter">

    <script>
        document.querySelector('#room-name-input').focus();
        document.querySelector('#room-name-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#room-name-submit').click();
            }
        };

        document.querySelector('#room-name-submit').onclick = function(e) {
            var roomName = document.querySelector('#room-name-input').value;
            window.location.pathname = '/chat/' + roomName + '/';
        };
    </script>
{% endblock content %}

myproject/chat/templates/chat/room.html
{% extends 'layout.html' %}
{% block title %}
Chatroom {{room_name}}
{% endblock title %}
{% block content %}
<textarea id="chat-log" cols="100" rows="20"></textarea><br>
    <input id="chat-message-input" type="text" size="100"><br>
    <input id="chat-message-submit" type="button" value="Send">
    {{ room_name|json_script:"room-name" }}
    <script>
        const roomName = JSON.parse(document.getElementById('room-name').textContent);

        const chatSocket = new WebSocket(
            'ws://'
            + window.location.host
            + '/ws/chat/'
            + roomName
            + '/'
        );

        chatSocket.onmessage = function(e) {
            const data = JSON.parse(e.data);
            document.querySelector('#chat-log').value += (data.message + '\n');
        };

        chatSocket.onclose = function(e) {
            console.error('Chat socket closed unexpectedly');
        };

        document.querySelector('#chat-message-input').focus();
        {% for chat in chats %}        
            console.log("testtt");
            document.querySelector('#chat-log').value += ("{{chat.body}}" + '\n');
        {% endfor %}

        document.querySelector('#chat-message-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#chat-message-submit').click();
            }
        };

        document.querySelector('#chat-message-submit').onclick = function(e) {
            const messageInputDom = document.querySelector('#chat-message-input');
            const message = messageInputDom.value;
            chatSocket.send(JSON.stringify({
                'message': message
            }));
            messageInputDom.value = '';
        };
    </script>
{% endblock content %}

myproject/post/templates/posts/post_new.html
{% extends 'layout.html' %}
{% block title%}
    New Post
{% endblock %}
{% block content %}
<section>
<h1>
    New Post
</h1>

<form class="form-with-validation" action="{% url "posts:new-post" %}" method="POST" enctype="multipart/form-data">

    {% csrf_token %}
    {{ form }}
    <button class="form-submit">Add Post</button>
</form>
</section>
{% endblock %}

myproject/post/templates/posts/post_page.html
{% extends 'layout.html' %}
{% block title%}
    {{post.title}}
{% endblock %}
{% block content %}
<section>
    <img class="banner" src="{{post.banner.url}}" alt="{{post.title}}">
    <h1>{{post.title}}</h1>
        <p>
            {{post.date}}
        </p>
        <p>
            {{post.body}}
        </p>
</section>
{% endblock %}

myproject/post/templates/posts/posts_list.html
{% extends 'layout.html' %}
{% block title%}
    Posts
{% endblock %}
{% block content %}
<section>

    <h1>Posts</h1>
    {% for post in posts %}
    <article class="post">
        <h2>
            <a href="{% url 'posts:page' slug=post.slug %}">
            {{post.title}}
            </a>
        </h2>
        <p>
            {{post.date}} 
            by: {{post.author}}
        </p>
        <p>
            {{post.body}}
        </p>
    </article>
    {% endfor%}
</section>
{% endblock %}

myproject/templates/about.html
{% extends 'layout.html' %}
{% block title%}
    About
{% endblock %}
{% block content %}
    <h1>About</h1>
    <p>Check Out My <a href="/">Home</a> page.</p>
{% endblock %}

myproject/templates/homepage.html
{% extends 'layout.html' %}
{% block title%}
    Home
{% endblock %}
{% block content %}
    <h1>Home</h1>
    <p>Check Out My <a href="/about">About</a> page.</p>
{% endblock %}

myproject/templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
            Django App
        {% endblock %}
    </title>
    
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/main.js' %}" defer></script>
</head>
<body>
    <nav>
        {% if user.is_authenticated %}        
        <h2>Welcome, {{user.username}}</h2> | 
        {% endif %}
        <a href="/">Home</a> | 
        <a href="/about" >About</a> | 
        <a href="/chat" >Chat</a> | 
        
        <a href="{% url 'posts:list'%}" >News </a> | 
        <a href="{% url 'users:list'%}" >Users </a> | 
        {% if user.is_authenticated %}
        <a href="{% url 'posts:new-post'%}" >New Post </a> | 
        
        <form class="logout" action="{% url 'users:logout' %}" method="POST">
            {% csrf_token %}
            <button class="logout-button">Logout </button>
        </form>
        
        {% else %}
        <a href="{% url 'users:login'%}" >Login </a> | 
        {% endif %}
    </nav>
    <main>
        {% block content%}
        {% endblock %}
    </main>
</body>
</html>

myproject/users/templates/login.html
{% extends 'layout.html' %}
{% block title%}
    Login
{% endblock %}
{% block content %}
    <h1>login here</h1>
    <form class="form-with-validation" action="{% url "users:login" %}" method="POST">
        {% csrf_token %}
        {{ form }}
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{request.GET.next}}">
        {% endif %}
        <button class="submit-button">Submit</button>
    </form>

{% endblock %}

myproject/users/templates/register.html
{% extends 'layout.html' %}
{% block title%}
    Register
{% endblock %}
{% block content %}
    <h1>register here</h1>
    <form class="form-with-validation" action="{% url "users:register" %}" method="POST">
        {% csrf_token %}
        {{ form }}
        <button class="submit-button">Submit</button>
    </form>

{% endblock %}

myproject/users/templates/users/user_list.html
{% extends 'layout.html' %}
{% block title%}
    Users
{% endblock %}
{% block content %}
<section>

    <h1>Users</h1>
    {% for user in users %}
    <article class="users">
        <a href="{% url 'users:page' userid=user.userid %}">
        <h2>
            {{user.name}}
        </h2>
    </a>
        <p>
            {{user.date}}
        </p>
        <p>
            {{user.userid}}
        </p>
    </article>
    {% endfor%}

    <a href="{% url 'users:register' %}">
        <h1>Register User</h1>
    </a>
    
</section>
{% endblock %}

myproject/users/templates/users/user_page.html
{% extends 'layout.html' %}
{% block title%}
    {{user.name}}
{% endblock %}
{% block content %}
<section>
    <h1>{{user.name}}</h1>
        <p>
            {{user.date}}
        </p>
        <p>
            {{user.userid}}
        </p>
</section>
{% endblock %}